### PR TITLE
fix Inner Join typo

### LINKED ISSUE #1339: " INNER JOIN"  typo
platform/view/services/storage/driver/sql/query/common/table.go  str 97: Inner: " INNER JOIN", (must be Inner: " INNER JOIN ")

### PR DESCRIPTION
**Pull request by FainaGS**

### CODE REVIEW

File: platform/view/services/storage/driver/sql/query/select/query_test.go [hunk 1]
```diff
@@ -38,14 +38,14 @@ func TestSelectSimple(t *testing.T) { //nolint:paralleltest
 	Expect(params).To(ConsistOf(5, 2, 1))
 }
 
-func TestSelectJoin(t *testing.T) { //nolint:paralleltest
+func TestSelectInnerJoin(t *testing.T) { //nolint:paralleltest
```
Comment (adecaro) [inline platform/view/services/storage/driver/sql/query/select/query_test.go:66]: please, add a new test, don't replace an existing one otherwise we don't test anymore `JoinAs(common.Right`. Thanks.

Comment (FainaGS) [reply platform/view/services/storage/driver/sql/query/select/query_test.go:66]: Done

**Review by adecaro — APPROVED** [review]
LGTM
